[template]
keys = [
    "/db/adapter",
    "/db/database",
    "/db/username",
    "/db/password",
    "/db/host",
    "/db/port",
]
owner = "root"
mode = "0644"
src = "database.tmpl"
dest = "/home/git/gitlab/config/database.yml"
reload_cmd = "/usr/sbin/supervisorctl restart gitlab"
